FROM nginx:alpine

RUN apk update && \
    apk add bash openssl curl inotify-tools && \
    rm -rf /var/cache/apk/*

# The monitor script looks to see if a reload/restart is requested
COPY entrypoint.sh monitor.sh /tmp/
RUN chmod +x /tmp/entrypoint.sh /tmp/monitor.sh

COPY conf /etc/nginx/

WORKDIR /var/www

RUN mkdir -p ssl           \
  members/log members/html \
  public/log public/html   \
  /monitor                 \
  /etc/nginx/sites-available /etc/nginx/sites-enabled

ENV SSL_ROOT=/var/www/ssl

VOLUME ["/etc/nginx/sites-available", "/etc/nginx/sites-enabled", "/monitor", "/var/www/ssl", "/var/www/members/html", "/var/www/public/html"]

ENTRYPOINT ["/tmp/entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]
